CREATE TABLE IF NOT EXISTS users (
 id BIGSERIAL PRIMARY KEY,
 name VARCHAR(40) NOT NULL,
 email VARCHAR(255) UNIQUE NOT NULL,
 password_hash TEXT NOT NULL,
 avatar TEXT,
 bio VARCHAR(280) DEFAULT '',
 role VARCHAR(20) NOT NULL DEFAULT 'user',
 verified BOOLEAN NOT NULL DEFAULT FALSE,
 vip_until TIMESTAMPTZ,
 call_pass_until TIMESTAMPTZ,
 gender VARCHAR(20) DEFAULT 'prefer_not_to_say',
 match_preference VARCHAR(20) DEFAULT 'any',
 is_guest BOOLEAN NOT NULL DEFAULT FALSE,
 guest_expires_at TIMESTAMPTZ,
 status VARCHAR(20) NOT NULL DEFAULT 'offline',
 age INTEGER,
 city VARCHAR(80) DEFAULT '',
 college VARCHAR(120) DEFAULT '',
 course VARCHAR(100) DEFAULT '',
 relationship_intent VARCHAR(40) DEFAULT 'open_to_connections',
 interests TEXT[] NOT NULL DEFAULT '{}',
 languages TEXT[] NOT NULL DEFAULT '{}',
 mode VARCHAR(20) NOT NULL DEFAULT 'dating',
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE users ADD COLUMN IF NOT EXISTS call_pass_until TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS gender VARCHAR(20) DEFAULT 'prefer_not_to_say';
ALTER TABLE users ADD COLUMN IF NOT EXISTS match_preference VARCHAR(20) DEFAULT 'any';
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_guest BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS guest_expires_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS age INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS city VARCHAR(80) DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS college VARCHAR(120) DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS course VARCHAR(100) DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS relationship_intent VARCHAR(40) DEFAULT 'open_to_connections';
ALTER TABLE users ADD COLUMN IF NOT EXISTS interests TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE users ADD COLUMN IF NOT EXISTS languages TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE users ADD COLUMN IF NOT EXISTS mode VARCHAR(20) NOT NULL DEFAULT 'dating';
CREATE INDEX IF NOT EXISTS idx_users_discovery ON users(status,gender,mode);

CREATE TABLE IF NOT EXISTS rooms (id BIGSERIAL PRIMARY KEY,name VARCHAR(80) UNIQUE NOT NULL,slug VARCHAR(100) UNIQUE NOT NULL,language VARCHAR(40) NOT NULL,flag VARCHAR(10) NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS room_members (room_id BIGINT REFERENCES rooms(id) ON DELETE CASCADE,user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),PRIMARY KEY(room_id,user_id));
CREATE TABLE IF NOT EXISTS groups (id BIGSERIAL PRIMARY KEY,name VARCHAR(100) UNIQUE NOT NULL,slug VARCHAR(120) UNIQUE NOT NULL,category VARCHAR(60) NOT NULL,description VARCHAR(300) DEFAULT '',icon VARCHAR(20) DEFAULT '👥',city VARCHAR(80) DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS group_members (group_id BIGINT REFERENCES groups(id) ON DELETE CASCADE,user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),PRIMARY KEY(group_id,user_id));
CREATE INDEX IF NOT EXISTS idx_group_members_user ON group_members(user_id);
CREATE TABLE IF NOT EXISTS events (id BIGSERIAL PRIMARY KEY,group_id BIGINT REFERENCES groups(id) ON DELETE CASCADE,creator_id BIGINT REFERENCES users(id) ON DELETE CASCADE,title VARCHAR(120) NOT NULL,description VARCHAR(500) DEFAULT '',starts_at TIMESTAMPTZ NOT NULL,location VARCHAR(150) DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS event_members (event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),PRIMARY KEY(event_id,user_id));

CREATE TABLE IF NOT EXISTS messages (id BIGSERIAL PRIMARY KEY,sender_id BIGINT REFERENCES users(id) ON DELETE CASCADE,room_id BIGINT REFERENCES rooms(id) ON DELETE CASCADE,receiver_id BIGINT REFERENCES users(id) ON DELETE CASCADE,group_id BIGINT REFERENCES groups(id) ON DELETE CASCADE,body TEXT NOT NULL CHECK(length(body)<=2000),attachment_data TEXT,attachment_mime VARCHAR(50),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
ALTER TABLE messages ADD COLUMN IF NOT EXISTS attachment_data TEXT;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS attachment_mime VARCHAR(50);
ALTER TABLE messages ADD COLUMN IF NOT EXISTS group_id BIGINT REFERENCES groups(id) ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_messages_room_time ON messages(room_id,created_at);
CREATE INDEX IF NOT EXISTS idx_messages_dm ON messages(sender_id,receiver_id,created_at);
CREATE INDEX IF NOT EXISTS idx_messages_group ON messages(group_id,created_at);

CREATE TABLE IF NOT EXISTS swipes (id BIGSERIAL PRIMARY KEY,swiper_id BIGINT REFERENCES users(id) ON DELETE CASCADE,target_id BIGINT REFERENCES users(id) ON DELETE CASCADE,direction VARCHAR(10) NOT NULL CHECK(direction IN ('like','pass')),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(swiper_id,target_id));
CREATE TABLE IF NOT EXISTS matches (id BIGSERIAL PRIMARY KEY,user1_id BIGINT REFERENCES users(id) ON DELETE CASCADE,user2_id BIGINT REFERENCES users(id) ON DELETE CASCADE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(user1_id,user2_id),CHECK(user1_id<user2_id));
CREATE INDEX IF NOT EXISTS idx_swipes_user ON swipes(swiper_id,direction);
CREATE INDEX IF NOT EXISTS idx_matches_users ON matches(user1_id,user2_id);

CREATE TABLE IF NOT EXISTS compatibility_questions (id BIGSERIAL PRIMARY KEY,question TEXT NOT NULL,option_a VARCHAR(120) NOT NULL,option_b VARCHAR(120) NOT NULL,category VARCHAR(50) NOT NULL DEFAULT 'lifestyle');
CREATE TABLE IF NOT EXISTS compatibility_answers (user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,question_id BIGINT REFERENCES compatibility_questions(id) ON DELETE CASCADE,answer VARCHAR(120) NOT NULL,PRIMARY KEY(user_id,question_id));

CREATE TABLE IF NOT EXISTS reports (id BIGSERIAL PRIMARY KEY,reporter_id BIGINT REFERENCES users(id) ON DELETE CASCADE,reported_user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,message_id BIGINT REFERENCES messages(id) ON DELETE SET NULL,reason VARCHAR(100) NOT NULL,details VARCHAR(1000) DEFAULT '',status VARCHAR(20) NOT NULL DEFAULT 'open',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS blocks (blocker_id BIGINT REFERENCES users(id) ON DELETE CASCADE,blocked_id BIGINT REFERENCES users(id) ON DELETE CASCADE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),PRIMARY KEY(blocker_id,blocked_id));
CREATE TABLE IF NOT EXISTS subscriptions (id BIGSERIAL PRIMARY KEY,user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,provider VARCHAR(30) NOT NULL DEFAULT 'razorpay',product VARCHAR(30) NOT NULL DEFAULT 'vip',order_id VARCHAR(100),payment_id VARCHAR(100),status VARCHAR(30) NOT NULL DEFAULT 'created',amount_paise INTEGER NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS product VARCHAR(30) NOT NULL DEFAULT 'vip';
