import jwt from "jsonwebtoken";
import bcrypt from "bcryptjs";
import crypto from "node:crypto";
import {q} from "./db.js";
const secret=()=>{if(!process.env.JWT_SECRET||process.env.JWT_SECRET.length<32)throw new Error("JWT_SECRET must be at least 32 characters");return process.env.JWT_SECRET};
export function sign(user){return jwt.sign({id:user.id,role:user.role,name:user.name},secret(),{expiresIn:user.is_guest?"24h":"7d"})}
export function verifyToken(token){return jwt.verify(token,secret())}
export async function auth(req,res,next){try{const h=req.headers.authorization||"";if(!h.startsWith("Bearer "))throw Error();const payload=verifyToken(h.slice(7));const r=await q("SELECT id,name,role,status,is_guest,guest_expires_at FROM users WHERE id=$1",[payload.id]);if(!r.rowCount||r.rows[0].status==="banned")return res.status(403).json({error:"Account unavailable"});if(r.rows[0].is_guest&&r.rows[0].guest_expires_at&&new Date(r.rows[0].guest_expires_at)<new Date())return res.status(401).json({error:"Guest session expired"});req.user=r.rows[0];next()}catch{res.status(401).json({error:"Authentication required"})}}
export function optionalAuth(req,_res,next){try{const h=req.headers.authorization||"";req.user=h.startsWith("Bearer ")?verifyToken(h.slice(7)):null}catch{req.user=null}next()}
export async function register(name,email,password,profile={}){const normalized=email.toLowerCase();const exists=await q("SELECT id FROM users WHERE email=$1",[normalized]);if(exists.rowCount)throw Object.assign(new Error("Email already registered"),{status:409});const hash=await bcrypt.hash(password,12);const gender=profile.gender||"prefer_not_to_say",pref=profile.matchPreference||"any";const mode=profile.mode||"dating";const age=Number.isInteger(profile.age)?profile.age:null;const city=profile.city||"",course=profile.course||"",college=profile.college||"",intent=profile.relationshipIntent||"open_to_connections",interests=Array.isArray(profile.interests)?profile.interests:[],languages=Array.isArray(profile.languages)?profile.languages:[];const r=await q("INSERT INTO users(name,email,password_hash,status,gender,match_preference,mode,age,city,course,college,relationship_intent,interests,languages) VALUES($1,$2,$3,'online',$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING id,name,email,role,verified,vip_until,call_pass_until,status,bio,avatar,gender,match_preference,is_guest,mode,age,city,course,college,relationship_intent,interests,languages",[name,normalized,hash,gender,pref,mode,age,city,course,college,intent,interests,languages]);return r.rows[0]}
export async function guest(){const id=crypto.randomBytes(5).toString("hex");const email=`guest_${id}@guest.local`;const password=crypto.randomBytes(24).toString("hex");const hash=await bcrypt.hash(password,10);const name=`Guest_${id.slice(0,6)}`;const r=await q("INSERT INTO users(name,email,password_hash,status,gender,match_preference,is_guest,guest_expires_at,mode) VALUES($1,$2,$3,'online','prefer_not_to_say','any',true,NOW()+INTERVAL '24 hours','community') RETURNING id,name,email,role,verified,vip_until,call_pass_until,status,bio,avatar,gender,match_preference,is_guest,guest_expires_at,mode,age,city,course,college,relationship_intent,interests,languages",[name,email,hash]);return r.rows[0]}
export async function login(email,password){const r=await q("SELECT * FROM users WHERE email=$1",[String(email||"").toLowerCase()]);if(!r.rowCount||!(await bcrypt.compare(password||"",r.rows[0].password_hash)))throw Object.assign(new Error("Invalid email or password"),{status:401});const u=r.rows[0];if(u.status==="banned")throw Object.assign(new Error("This account is banned"),{status:403});if(u.is_guest&&u.guest_expires_at&&new Date(u.guest_expires_at)<new Date())throw Object.assign(new Error("Guest session expired"),{status:401});await q("UPDATE users SET status='online' WHERE id=$1",[u.id]);delete u.password_hash;return u}
